
package com.nd.ws.billing.account.create;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AccountCreateInterface", targetNamespace = "http://com/nd/ws/billing/account/create", wsdlLocation = "/META-INF/wsdl/AccountCreateInterface.wsdl")
public class AccountCreateInterface
    extends Service
{

    private final static URL ACCOUNTCREATEINTERFACE_WSDL_LOCATION;
    private final static WebServiceException ACCOUNTCREATEINTERFACE_EXCEPTION;
    private final static QName ACCOUNTCREATEINTERFACE_QNAME = new QName("http://com/nd/ws/billing/account/create", "AccountCreateInterface");

    static {
        ACCOUNTCREATEINTERFACE_WSDL_LOCATION = com.nd.ws.billing.account.create.AccountCreateInterface.class.getResource("/META-INF/wsdl/AccountCreateInterface.wsdl");
        WebServiceException e = null;
        if (ACCOUNTCREATEINTERFACE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/META-INF/wsdl/AccountCreateInterface.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        ACCOUNTCREATEINTERFACE_EXCEPTION = e;
    }

    public AccountCreateInterface() {
        super(__getWsdlLocation(), ACCOUNTCREATEINTERFACE_QNAME);
    }

    public AccountCreateInterface(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCOUNTCREATEINTERFACE_QNAME, features);
    }

    public AccountCreateInterface(URL wsdlLocation) {
        super(wsdlLocation, ACCOUNTCREATEINTERFACE_QNAME);
    }

    public AccountCreateInterface(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCOUNTCREATEINTERFACE_QNAME, features);
    }

    public AccountCreateInterface(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountCreateInterface(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IAccountCreateInterface
     */
    @WebEndpoint(name = "AccountCreateInterfacePort")
    public IAccountCreateInterface getAccountCreateInterfacePort() {
        return super.getPort(new QName("http://com/nd/ws/billing/account/create", "AccountCreateInterfacePort"), IAccountCreateInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAccountCreateInterface
     */
    @WebEndpoint(name = "AccountCreateInterfacePort")
    public IAccountCreateInterface getAccountCreateInterfacePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com/nd/ws/billing/account/create", "AccountCreateInterfacePort"), IAccountCreateInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCOUNTCREATEINTERFACE_EXCEPTION!= null) {
            throw ACCOUNTCREATEINTERFACE_EXCEPTION;
        }
        return ACCOUNTCREATEINTERFACE_WSDL_LOCATION;
    }

}
