
package com.nd.ws.billing.account.create;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.nd.ws.billing.account.createinterface.AccountWorkflowRequest;
import com.nd.ws.billing.account.createinterface.AccountWorkflowResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IAccountCreateInterface", targetNamespace = "http://com/nd/ws/billing/account/createinterface")
@XmlSeeAlso({
    com.nd.ws.billing.account.createinterface.ObjectFactory.class,
    com.nd.billing.model.account.response.ObjectFactory.class
})
public interface IAccountCreateInterface {


    /**
     * 
     * @param accountWorkflowRequest
     * @return
     *     returns com.nd.ws.billing.account.createinterface.AccountWorkflowResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "executeAccountCreate", targetNamespace = "http://com/nd/ws/billing/account/createinterface", className = "com.nd.ws.billing.account.createinterface.ExecuteAccountCreate")
    @ResponseWrapper(localName = "executeAccountCreateResponse", targetNamespace = "http://com/nd/ws/billing/account/createinterface", className = "com.nd.ws.billing.account.createinterface.ExecuteAccountCreateResponse")
    @Action(input = "http://com/nd/ws/billing/account/createinterface/IAccountCreateInterface/executeAccountCreateRequest", output = "http://com/nd/ws/billing/account/createinterface/IAccountCreateInterface/executeAccountCreateResponse")
    public AccountWorkflowResponse executeAccountCreate(
        @WebParam(name = "AccountWorkflowRequest", targetNamespace = "")
        AccountWorkflowRequest accountWorkflowRequest);

}
