
package com.coverall.mt.webservices.producerupload.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProducerUploadServicePortType", targetNamespace = "http://impl.producerupload.webservices.mt.coverall.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProducerUploadServicePortType {


    /**
     * 
     * @param request
     * @return
     *     returns com.coverall.mt.webservices.producerupload.impl.ProducerUploadServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "producerUpload", targetNamespace = "http://impl.producerupload.webservices.mt.coverall.com/", className = "com.coverall.mt.webservices.producerupload.impl.ProducerUpload")
    @ResponseWrapper(localName = "producerUploadResponse", targetNamespace = "http://impl.producerupload.webservices.mt.coverall.com/", className = "com.coverall.mt.webservices.producerupload.impl.ProducerUploadResponse")
    public ProducerUploadServiceResponse producerUpload(
        @WebParam(name = "request", targetNamespace = "")
        ProducerUploadServiceRequest request);

}
