
package com.coverall.mt.webservices.producerupload.impl;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProducerUploadService", targetNamespace = "http://impl.producerupload.webservices.mt.coverall.com/", wsdlLocation = "/META-INF/wsdl/ProducerUploadService.wsdl")
public class ProducerUploadService
    extends Service
{

    private final static URL PRODUCERUPLOADSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCERUPLOADSERVICE_EXCEPTION;
    private final static QName PRODUCERUPLOADSERVICE_QNAME = new QName("http://impl.producerupload.webservices.mt.coverall.com/", "ProducerUploadService");

    static {
        PRODUCERUPLOADSERVICE_WSDL_LOCATION = com.coverall.mt.webservices.producerupload.impl.ProducerUploadService.class.getResource("/META-INF/wsdl/ProducerUploadService.wsdl");
        WebServiceException e = null;
        if (PRODUCERUPLOADSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/META-INF/wsdl/ProducerUploadService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PRODUCERUPLOADSERVICE_EXCEPTION = e;
    }

    public ProducerUploadService() {
        super(__getWsdlLocation(), PRODUCERUPLOADSERVICE_QNAME);
    }

    public ProducerUploadService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCERUPLOADSERVICE_QNAME, features);
    }

    public ProducerUploadService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCERUPLOADSERVICE_QNAME);
    }

    public ProducerUploadService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCERUPLOADSERVICE_QNAME, features);
    }

    public ProducerUploadService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProducerUploadService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProducerUploadServicePortType
     */
    @WebEndpoint(name = "ProducerUploadServicePort")
    public ProducerUploadServicePortType getProducerUploadServicePort() {
        return super.getPort(new QName("http://impl.producerupload.webservices.mt.coverall.com/", "ProducerUploadServicePort"), ProducerUploadServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProducerUploadServicePortType
     */
    @WebEndpoint(name = "ProducerUploadServicePort")
    public ProducerUploadServicePortType getProducerUploadServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.producerupload.webservices.mt.coverall.com/", "ProducerUploadServicePort"), ProducerUploadServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCERUPLOADSERVICE_EXCEPTION!= null) {
            throw PRODUCERUPLOADSERVICE_EXCEPTION;
        }
        return PRODUCERUPLOADSERVICE_WSDL_LOCATION;
    }

}
