
package com.majescomastek.stgicd.ws.meta.inboundinstrumentinformation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.majescomastek.stgicd.ws.meta.authentication.Authentication;
import com.majescomastek.stgicd.ws.meta.inboundinstrumentinformation.inboundinstrumentinformation.InboundInstrumentsDetail;
import com.majescomastek.stgicd.ws.meta.inboundinstrumentinformation.inboundinstrumentinformation.InstrumentDetailResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InBoundInstrumentInformation", targetNamespace = "http://com/majescomastek/stgicd/ws/meta/inboundinstrumentinformation")
@XmlSeeAlso({
    com.majescomastek.stgicd.ws.meta.authentication.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.inboundinstrumentinformation.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.inboundinstrumentinformation.inboundinstrumentinformation.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.inboundinstrumentinformation.paymentinstrumentinforesponse.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.inboundinstrumentinformation.requestheader.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.inboundinstrumentinformation.requestresponse.ObjectFactory.class
})
public interface InBoundInstrumentInformation {


    /**
     * 
     * @param userAuthentication
     * @param inputMsg
     * @return
     *     returns com.majescomastek.stgicd.ws.meta.inboundinstrumentinformation.inboundinstrumentinformation.InstrumentDetailResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "service", targetNamespace = "http://com/majescomastek/stgicd/ws/meta/inboundinstrumentinformation", className = "com.majescomastek.stgicd.ws.meta.inboundinstrumentinformation.Service")
    @ResponseWrapper(localName = "serviceResponse", targetNamespace = "http://com/majescomastek/stgicd/ws/meta/inboundinstrumentinformation", className = "com.majescomastek.stgicd.ws.meta.inboundinstrumentinformation.ServiceResponse")
    public InstrumentDetailResponse service(
        @WebParam(name = "inputMsg", targetNamespace = "")
        InboundInstrumentsDetail inputMsg,
        @WebParam(name = "UserAuthentication", targetNamespace = "")
        Authentication userAuthentication)
        throws Exception_Exception
    ;

}
