
package com.majescomastek.stgicd.ws.meta.inboundinstrumentinformation;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InBoundInstrumentInformation", targetNamespace = "http://com/majescomastek/stgicd/ws/meta/inboundinstrumentinformation", wsdlLocation = "/META-INF/wsdl/InBoundInstrumentInformation.wsdl")
public class InBoundInstrumentInformation_Service
    extends Service
{

    private final static URL INBOUNDINSTRUMENTINFORMATION_WSDL_LOCATION;
    private final static WebServiceException INBOUNDINSTRUMENTINFORMATION_EXCEPTION;
    private final static QName INBOUNDINSTRUMENTINFORMATION_QNAME = new QName("http://com/majescomastek/stgicd/ws/meta/inboundinstrumentinformation", "InBoundInstrumentInformation");

    static {
        INBOUNDINSTRUMENTINFORMATION_WSDL_LOCATION = com.majescomastek.stgicd.ws.meta.inboundinstrumentinformation.InBoundInstrumentInformation_Service.class.getResource("/META-INF/wsdl/InBoundInstrumentInformation.wsdl");
        WebServiceException e = null;
        if (INBOUNDINSTRUMENTINFORMATION_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/META-INF/wsdl/InBoundInstrumentInformation.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        INBOUNDINSTRUMENTINFORMATION_EXCEPTION = e;
    }

    public InBoundInstrumentInformation_Service() {
        super(__getWsdlLocation(), INBOUNDINSTRUMENTINFORMATION_QNAME);
    }

    public InBoundInstrumentInformation_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), INBOUNDINSTRUMENTINFORMATION_QNAME, features);
    }

    public InBoundInstrumentInformation_Service(URL wsdlLocation) {
        super(wsdlLocation, INBOUNDINSTRUMENTINFORMATION_QNAME);
    }

    public InBoundInstrumentInformation_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INBOUNDINSTRUMENTINFORMATION_QNAME, features);
    }

    public InBoundInstrumentInformation_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InBoundInstrumentInformation_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InBoundInstrumentInformation
     */
    @WebEndpoint(name = "InBoundInstrumentInformationPort")
    public InBoundInstrumentInformation getInBoundInstrumentInformationPort() {
        return super.getPort(new QName("http://com/majescomastek/stgicd/ws/meta/inboundinstrumentinformation", "InBoundInstrumentInformationPort"), InBoundInstrumentInformation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InBoundInstrumentInformation
     */
    @WebEndpoint(name = "InBoundInstrumentInformationPort")
    public InBoundInstrumentInformation getInBoundInstrumentInformationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com/majescomastek/stgicd/ws/meta/inboundinstrumentinformation", "InBoundInstrumentInformationPort"), InBoundInstrumentInformation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INBOUNDINSTRUMENTINFORMATION_EXCEPTION!= null) {
            throw INBOUNDINSTRUMENTINFORMATION_EXCEPTION;
        }
        return INBOUNDINSTRUMENTINFORMATION_WSDL_LOCATION;
    }

}
