
package com.majescomastek.stgicd.ws.meta.entityinterface;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EntityInterface", targetNamespace = "http://com/majescomastek/stgicd/ws/meta/entityinterface", wsdlLocation = "/META-INF/wsdl/EntityInterface.wsdl")
public class EntityInterface_Service
    extends Service
{

    private final static URL ENTITYINTERFACE_WSDL_LOCATION;
    private final static WebServiceException ENTITYINTERFACE_EXCEPTION;
    private final static QName ENTITYINTERFACE_QNAME = new QName("http://com/majescomastek/stgicd/ws/meta/entityinterface", "EntityInterface");

    static {
        ENTITYINTERFACE_WSDL_LOCATION = com.majescomastek.stgicd.ws.meta.entityinterface.EntityInterface_Service.class.getResource("/META-INF/wsdl/EntityInterface.wsdl");
        WebServiceException e = null;
        if (ENTITYINTERFACE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/META-INF/wsdl/EntityInterface.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        ENTITYINTERFACE_EXCEPTION = e;
    }

    public EntityInterface_Service() {
        super(__getWsdlLocation(), ENTITYINTERFACE_QNAME);
    }

    public EntityInterface_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENTITYINTERFACE_QNAME, features);
    }

    public EntityInterface_Service(URL wsdlLocation) {
        super(wsdlLocation, ENTITYINTERFACE_QNAME);
    }

    public EntityInterface_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENTITYINTERFACE_QNAME, features);
    }

    public EntityInterface_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EntityInterface_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EntityInterface
     */
    @WebEndpoint(name = "EntityInterfacePort")
    public EntityInterface getEntityInterfacePort() {
        return super.getPort(new QName("http://com/majescomastek/stgicd/ws/meta/entityinterface", "EntityInterfacePort"), EntityInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EntityInterface
     */
    @WebEndpoint(name = "EntityInterfacePort")
    public EntityInterface getEntityInterfacePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com/majescomastek/stgicd/ws/meta/entityinterface", "EntityInterfacePort"), EntityInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENTITYINTERFACE_EXCEPTION!= null) {
            throw ENTITYINTERFACE_EXCEPTION;
        }
        return ENTITYINTERFACE_WSDL_LOCATION;
    }

}
