
package com.majescomastek.stgicd.ws.meta.entityinterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.majescomastek.stgicd.ws.meta.authentication.Authentication;
import com.majescomastek.stgicd.ws.meta.entityinterface.entityinterface.InboundEntityInterface;
import com.majescomastek.stgicd.ws.meta.entityinterface.entityinterface.OutputTransaction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EntityInterface", targetNamespace = "http://com/majescomastek/stgicd/ws/meta/entityinterface")
@XmlSeeAlso({
    com.majescomastek.stgicd.ws.meta.authentication.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.entityinterface.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.entityinterface.entity.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.entityinterface.entityinterface.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.entityinterface.entityresponse.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.entityinterface.requestheader.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.entityinterface.requestresponse.ObjectFactory.class
})
public interface EntityInterface {


    /**
     * 
     * @param userAuthentication
     * @param inputMsg
     * @return
     *     returns com.majescomastek.stgicd.ws.meta.entityinterface.entityinterface.OutputTransaction
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "service", targetNamespace = "http://com/majescomastek/stgicd/ws/meta/entityinterface", className = "com.majescomastek.stgicd.ws.meta.entityinterface.Service")
    @ResponseWrapper(localName = "serviceResponse", targetNamespace = "http://com/majescomastek/stgicd/ws/meta/entityinterface", className = "com.majescomastek.stgicd.ws.meta.entityinterface.ServiceResponse")
    public OutputTransaction service(
        @WebParam(name = "inputMsg", targetNamespace = "")
        InboundEntityInterface inputMsg,
        @WebParam(name = "UserAuthentication", targetNamespace = "")
        Authentication userAuthentication)
        throws Exception_Exception
    ;

}
