
package com.majescomastek.stgicd.ws.meta.suspendreleaseinterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.majescomastek.stgicd.ws.meta.authentication.Authentication;
import com.majescomastek.stgicd.ws.meta.suspendreleaseinterface.suspendreleaseinterface.Servicerequest;
import com.majescomastek.stgicd.ws.meta.suspendreleaseinterface.suspendreleaseinterface.Serviceresponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SuspendReleaseInterface", targetNamespace = "http://com/majescomastek/stgicd/ws/meta/suspendreleaseinterface")
@XmlSeeAlso({
    com.majescomastek.stgicd.ws.meta.authentication.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.suspendreleaseinterface.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.suspendreleaseinterface.holdreleasedetails.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.suspendreleaseinterface.holdreleaseresponse.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.suspendreleaseinterface.inboundrequest.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.suspendreleaseinterface.outboundresponse.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.suspendreleaseinterface.suspendreleaseinterface.ObjectFactory.class
})
public interface SuspendReleaseInterface {


    /**
     * 
     * @param userAuthentication
     * @param inputMsg
     * @return
     *     returns com.majescomastek.stgicd.ws.meta.suspendreleaseinterface.suspendreleaseinterface.Serviceresponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "service", targetNamespace = "http://com/majescomastek/stgicd/ws/meta/suspendreleaseinterface", className = "com.majescomastek.stgicd.ws.meta.suspendreleaseinterface.Service")
    @ResponseWrapper(localName = "serviceResponse", targetNamespace = "http://com/majescomastek/stgicd/ws/meta/suspendreleaseinterface", className = "com.majescomastek.stgicd.ws.meta.suspendreleaseinterface.ServiceResponse")
    public Serviceresponse service(
        @WebParam(name = "inputMsg", targetNamespace = "")
        Servicerequest inputMsg,
        @WebParam(name = "UserAuthentication", targetNamespace = "")
        Authentication userAuthentication)
        throws Exception_Exception
    ;

}
