
package com.majescomastek.stgicd.ws.meta.suspendreleaseinterface;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SuspendReleaseInterface", targetNamespace = "http://com/majescomastek/stgicd/ws/meta/suspendreleaseinterface", wsdlLocation = "/META-INF/wsdl/SuspendReleaseInterface.wsdl")
public class SuspendReleaseInterface_Service
    extends Service
{

    private final static URL SUSPENDRELEASEINTERFACE_WSDL_LOCATION;
    private final static WebServiceException SUSPENDRELEASEINTERFACE_EXCEPTION;
    private final static QName SUSPENDRELEASEINTERFACE_QNAME = new QName("http://com/majescomastek/stgicd/ws/meta/suspendreleaseinterface", "SuspendReleaseInterface");

    static {
        SUSPENDRELEASEINTERFACE_WSDL_LOCATION = com.majescomastek.stgicd.ws.meta.suspendreleaseinterface.SuspendReleaseInterface_Service.class.getResource("/META-INF/wsdl/SuspendReleaseInterface.wsdl");
        WebServiceException e = null;
        if (SUSPENDRELEASEINTERFACE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/META-INF/wsdl/SuspendReleaseInterface.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        SUSPENDRELEASEINTERFACE_EXCEPTION = e;
    }

    public SuspendReleaseInterface_Service() {
        super(__getWsdlLocation(), SUSPENDRELEASEINTERFACE_QNAME);
    }

    public SuspendReleaseInterface_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUSPENDRELEASEINTERFACE_QNAME, features);
    }

    public SuspendReleaseInterface_Service(URL wsdlLocation) {
        super(wsdlLocation, SUSPENDRELEASEINTERFACE_QNAME);
    }

    public SuspendReleaseInterface_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUSPENDRELEASEINTERFACE_QNAME, features);
    }

    public SuspendReleaseInterface_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SuspendReleaseInterface_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SuspendReleaseInterface
     */
    @WebEndpoint(name = "SuspendReleaseInterfacePort")
    public SuspendReleaseInterface getSuspendReleaseInterfacePort() {
        return super.getPort(new QName("http://com/majescomastek/stgicd/ws/meta/suspendreleaseinterface", "SuspendReleaseInterfacePort"), SuspendReleaseInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SuspendReleaseInterface
     */
    @WebEndpoint(name = "SuspendReleaseInterfacePort")
    public SuspendReleaseInterface getSuspendReleaseInterfacePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com/majescomastek/stgicd/ws/meta/suspendreleaseinterface", "SuspendReleaseInterfacePort"), SuspendReleaseInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUSPENDRELEASEINTERFACE_EXCEPTION!= null) {
            throw SUSPENDRELEASEINTERFACE_EXCEPTION;
        }
        return SUSPENDRELEASEINTERFACE_WSDL_LOCATION;
    }

}
