package com.stgmastek.monitor.ws.server.services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.10 Generated source version: 2.2
 */
@WebService(name = "MonitorServices",
            targetNamespace = "http://services.server.ws.monitor.stgmastek.com/")
@XmlSeeAlso({
                ObjectFactory.class
            })
public interface MonitorServices
{


  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResBatchObjectVO
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getBatchObjectDetails",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.GetBatchObjectDetails")
  @ResponseWrapper(localName = "getBatchObjectDetailsResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.GetBatchObjectDetailsResponse")
  ResBatchObjectVO getBatchObjectDetails(
      @WebParam(name = "reqBatchDetails", targetNamespace = "")
          ReqBatchDetails reqBatchDetails);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResGraphVO
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getGraphData",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.GetGraphData")
  @ResponseWrapper(localName = "getGraphDataResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.GetGraphDataResponse")
  ResGraphVO getGraphData(
      @WebParam(name = "batch", targetNamespace = "")
          ReqBatch batch);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResCalendarVO
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getCalendars",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.GetCalendars")
  @ResponseWrapper(localName = "getCalendarsResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.GetCalendarsResponse")
  ResCalendarVO getCalendars(
      @WebParam(name = "calendarVO", targetNamespace = "")
          ReqCalendarVO calendarVO);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResInstallationVO
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "stopBatch",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.StopBatch")
  @ResponseWrapper(localName = "stopBatchResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.StopBatchResponse")
  ResInstallationVO stopBatch(
      @WebParam(name = "reqInstructionLog", targetNamespace = "")
          ReqInstructionLog reqInstructionLog);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResBatchInfo
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "processRequest",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.ProcessRequest")
  @ResponseWrapper(localName = "processRequestResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.ProcessRequestResponse")
  ResBatchInfo processRequest(
      @WebParam(name = "ExecuteReport", targetNamespace = "")
          ExecuteReport executeReport,
      @WebParam(name = "ReqInstructionLog", targetNamespace = "")
          ReqInstructionLog reqInstructionLog);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResInstructionVO
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "checkInstructionLog",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.CheckInstructionLog")
  @ResponseWrapper(localName = "checkInstructionLogResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.CheckInstructionLogResponse")
  ResInstructionVO checkInstructionLog(
      @WebParam(name = "reqInstructionLog", targetNamespace = "")
          ReqInstructionLog reqInstructionLog);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResDropDownEntry
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "retrieveDropDownEntries",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.RetrieveDropDownEntries")
  @ResponseWrapper(localName = "retrieveDropDownEntriesResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.RetrieveDropDownEntriesResponse")
  ResDropDownEntry retrieveDropDownEntries(
      @WebParam(name = "DropDownIdentifierList", targetNamespace = "")
          List<ConfigParameter> dropDownIdentifierList);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResInstallationEntitiesVO
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getBatchEntityData",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.GetBatchEntityData")
  @ResponseWrapper(localName = "getBatchEntityDataResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.GetBatchEntityDataResponse")
  ResInstallationEntitiesVO getBatchEntityData(
      @WebParam(name = "reqInstallationVO", targetNamespace = "")
          ReqInstallationVO reqInstallationVO);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResCalendarVO
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getCalendarData",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.GetCalendarData")
  @ResponseWrapper(localName = "getCalendarDataResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.GetCalendarDataResponse")
  ResCalendarVO getCalendarData(
      @WebParam(name = "calendarVO", targetNamespace = "")
          ReqCalendarVO calendarVO);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResRoleDetailsVO
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getRoleData",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.GetRoleData")
  @ResponseWrapper(localName = "getRoleDataResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.GetRoleDataResponse")
  ResRoleDetailsVO getRoleData();

  /**
   *
   */
  @WebMethod
  @RequestWrapper(localName = "stopMonitorServices",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.StopMonitorServices")
  @ResponseWrapper(localName = "stopMonitorServicesResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.StopMonitorServicesResponse")
  void stopMonitorServices();

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResInstallationVO
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getInstallationDetailsForBatch",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.GetInstallationDetailsForBatch")
  @ResponseWrapper(localName = "getInstallationDetailsForBatchResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.GetInstallationDetailsForBatchResponse")
  ResInstallationVO getInstallationDetailsForBatch(
      @WebParam(name = "batch", targetNamespace = "")
          ReqBatch batch);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResBatchInfo
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getBatchCompletedData",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.GetBatchCompletedData")
  @ResponseWrapper(localName = "getBatchCompletedDataResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.GetBatchCompletedDataResponse")
  ResBatchInfo getBatchCompletedData(
      @WebParam(name = "searchBatch", targetNamespace = "")
          ReqSearchBatch searchBatch);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResInstallationVO
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getInstallationData",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.GetInstallationData")
  @ResponseWrapper(localName = "getInstallationDataResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.GetInstallationDataResponse")
  ResInstallationVO getInstallationData(
      @WebParam(name = "batch", targetNamespace = "")
          ReqBatch batch);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResBatchDataVO
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getBatchInfo",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.GetBatchInfo")
  @ResponseWrapper(localName = "getBatchInfoResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.GetBatchInfoResponse")
  ResBatchDataVO getBatchInfo(
      @WebParam(name = "batch", targetNamespace = "")
          ReqBatch batch);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResFailedObjectVO
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getFaliedObjectDetails",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.GetFaliedObjectDetails")
  @ResponseWrapper(localName = "getFaliedObjectDetailsResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.GetFaliedObjectDetailsResponse")
  ResFailedObjectVO getFaliedObjectDetails(
      @WebParam(name = "reqListenerInfo", targetNamespace = "")
          ReqListenerInfo reqListenerInfo);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.BaseResponseVO
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "resetPassword",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.ResetPassword")
  @ResponseWrapper(localName = "resetPasswordResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.ResetPasswordResponse")
  BaseResponseVO resetPassword(
      @WebParam(name = "userProfile", targetNamespace = "")
          UserProfile userProfile);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResBatchInfo
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getBatchData",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.GetBatchData")
  @ResponseWrapper(localName = "getBatchDataResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.GetBatchDataResponse")
  ResBatchInfo getBatchData(
      @WebParam(name = "batch", targetNamespace = "")
          ReqBatch batch);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResListenerVO
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getListenerInfo",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.GetListenerInfo")
  @ResponseWrapper(localName = "getListenerInfoResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.GetListenerInfoResponse")
  ResListenerVO getListenerInfo(
      @WebParam(name = "batch", targetNamespace = "")
          ReqBatch batch);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResUserDetailsVO
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getUserInstallationRoleDetails",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.GetUserInstallationRoleDetails")
  @ResponseWrapper(localName = "getUserInstallationRoleDetailsResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.GetUserInstallationRoleDetailsResponse")
  ResUserDetailsVO getUserInstallationRoleDetails(
      @WebParam(name = "reqUserDetailsVO", targetNamespace = "")
          ReqUserDetailsVO reqUserDetailsVO);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResUserDetails
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "userAuthentication",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.UserAuthentication")
  @ResponseWrapper(localName = "userAuthenticationResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.UserAuthenticationResponse")
  ResUserDetails userAuthentication(
      @WebParam(name = "userCredentials", targetNamespace = "")
          UserCredentials userCredentials);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ExecuteReport
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "retrieveReportDropDownOptionForCompany",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.RetrieveReportDropDownOptionForCompany")
  @ResponseWrapper(localName = "retrieveReportDropDownOptionForCompanyResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.RetrieveReportDropDownOptionForCompanyResponse")
  ExecuteReport retrieveReportDropDownOptionForCompany(
      @WebParam(name = "UserProfile", targetNamespace = "")
          UserProfile userProfile);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.BaseResponseVO
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "updateUserProfile",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.UpdateUserProfile")
  @ResponseWrapper(localName = "updateUserProfileResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.UpdateUserProfileResponse")
  BaseResponseVO updateUserProfile(
      @WebParam(name = "reqUserDetailsVO", targetNamespace = "")
          ReqUserDetailsVO reqUserDetailsVO);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResProcessRequestScheduleVO
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "refreshProcessRequestScheduleData",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.RefreshProcessRequestScheduleData")
  @ResponseWrapper(localName = "refreshProcessRequestScheduleDataResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.RefreshProcessRequestScheduleDataResponse")
  ResProcessRequestScheduleVO refreshProcessRequestScheduleData(
      @WebParam(name = "processRequestScheduleVO", targetNamespace = "")
          ReqProcessRequestScheduleVO processRequestScheduleVO);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResMenuDetails
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getMenuDetails",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.GetMenuDetails")
  @ResponseWrapper(localName = "getMenuDetailsResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.GetMenuDetailsResponse")
  ResMenuDetails getMenuDetails(
      @WebParam(name = "userProfile", targetNamespace = "")
          UserProfile userProfile);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResSystemDetails
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getSystemInfo",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.GetSystemInfo")
  @ResponseWrapper(localName = "getSystemInfoResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.GetSystemInfoResponse")
  ResSystemDetails getSystemInfo(
      @WebParam(name = "batch", targetNamespace = "")
          ReqBatch batch);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResProcessRequestScheduleVO
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "cancelSchedule",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.CancelSchedule")
  @ResponseWrapper(localName = "cancelScheduleResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.CancelScheduleResponse")
  ResProcessRequestScheduleVO cancelSchedule(
      @WebParam(name = "processRequestScheduleVO", targetNamespace = "")
          ReqProcessRequestScheduleVO processRequestScheduleVO);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.BaseResponseVO
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "checkCompatibility",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.CheckCompatibility")
  @ResponseWrapper(localName = "checkCompatibilityResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.CheckCompatibilityResponse")
  BaseResponseVO checkCompatibility(
      @WebParam(name = "version", targetNamespace = "")
          ReqVersionVO version);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.BaseResponseVO
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "manageUser",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.ManageUser")
  @ResponseWrapper(localName = "manageUserResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.ManageUserResponse")
  BaseResponseVO manageUser(
      @WebParam(name = "reqUserDetailsVO", targetNamespace = "")
          ReqUserDetailsVO reqUserDetailsVO);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResProcessRequestScheduleVO
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getProcessRequestScheduleData",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.GetProcessRequestScheduleData")
  @ResponseWrapper(localName = "getProcessRequestScheduleDataResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.GetProcessRequestScheduleDataResponse")
  ResProcessRequestScheduleVO getProcessRequestScheduleData(
      @WebParam(name = "processRequestScheduleVO", targetNamespace = "")
          ReqProcessRequestScheduleVO processRequestScheduleVO);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResUserProfile
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getSecurityDetails",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.GetSecurityDetails")
  @ResponseWrapper(localName = "getSecurityDetailsResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.GetSecurityDetailsResponse")
  ResUserProfile getSecurityDetails(
      @WebParam(name = "userProfile", targetNamespace = "")
          UserProfile userProfile);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResInstallationVO
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getInstallationsList",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.GetInstallationsList")
  @ResponseWrapper(localName = "getInstallationsListResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.GetInstallationsListResponse")
  ResInstallationVO getInstallationsList();

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ExecuteReport
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "retrieveParametersForReport",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.RetrieveParametersForReport")
  @ResponseWrapper(localName = "retrieveParametersForReportResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.RetrieveParametersForReportResponse")
  ExecuteReport retrieveParametersForReport(
      @WebParam(name = "Report", targetNamespace = "")
          Report report);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.BaseResponseVO
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "changePassword",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.ChangePassword")
  @ResponseWrapper(localName = "changePasswordResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.ChangePasswordResponse")
  BaseResponseVO changePassword(
      @WebParam(name = "userCredentials", targetNamespace = "")
          UserCredentials userCredentials);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.ResBatchInfo
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "runBatch",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.RunBatch")
  @ResponseWrapper(localName = "runBatchResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.RunBatchResponse")
  ResBatchInfo runBatch(
      @WebParam(name = "reqInstructionLog", targetNamespace = "")
          ReqInstructionLog reqInstructionLog);

  /**
   * @return returns com.stgmastek.monitor.ws.server.services.BaseResponseVO
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "defineCalendar",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  className = "com.stgmastek.monitor.ws.server.services.DefineCalendar")
  @ResponseWrapper(localName = "defineCalendarResponse",
                   targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                   className = "com.stgmastek.monitor.ws.server.services.DefineCalendarResponse")
  BaseResponseVO defineCalendar(
      @WebParam(name = "calendarVO", targetNamespace = "")
          ReqCalendarVO calendarVO);

}
