package com.stgmastek.monitor.ws.server.services;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.10 Generated source version: 2.2
 */
@WebServiceClient(name = "MonitorServicesImplService",
                  targetNamespace = "http://services.server.ws.monitor.stgmastek.com/",
                  wsdlLocation = "/META-INF/wsdl/JBeamICD.wsdl")
public class MonitorServicesImplService
    extends Service
{

  private final static URL MONITORSERVICESIMPLSERVICE_WSDL_LOCATION;

  private final static WebServiceException MONITORSERVICESIMPLSERVICE_EXCEPTION;

  private final static QName MONITORSERVICESIMPLSERVICE_QNAME = new QName(
      "http://services.server.ws.monitor.stgmastek.com/", "MonitorServicesImplService");

  static
  {
    MONITORSERVICESIMPLSERVICE_WSDL_LOCATION = com.stgmastek.monitor.ws.server.services.MonitorServicesImplService.class.getResource(
        "/META-INF/wsdl/JBeamICD.wsdl");
    WebServiceException e = null;
    if (MONITORSERVICESIMPLSERVICE_WSDL_LOCATION == null)
    {
      e = new WebServiceException(
          "Cannot find '/META-INF/wsdl/JBeamICD.wsdl' wsdl. Place the resource correctly in the classpath.");
    }
    MONITORSERVICESIMPLSERVICE_EXCEPTION = e;
  }

  public MonitorServicesImplService()
  {
    super(__getWsdlLocation(), MONITORSERVICESIMPLSERVICE_QNAME);
  }

  public MonitorServicesImplService(WebServiceFeature... features)
  {
    super(__getWsdlLocation(), MONITORSERVICESIMPLSERVICE_QNAME, features);
  }

  public MonitorServicesImplService(URL wsdlLocation)
  {
    super(wsdlLocation, MONITORSERVICESIMPLSERVICE_QNAME);
  }

  public MonitorServicesImplService(URL wsdlLocation, WebServiceFeature... features)
  {
    super(wsdlLocation, MONITORSERVICESIMPLSERVICE_QNAME, features);
  }

  public MonitorServicesImplService(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  public MonitorServicesImplService(URL wsdlLocation, QName serviceName,
                                    WebServiceFeature... features)
  {
    super(wsdlLocation, serviceName, features);
  }

  private static URL __getWsdlLocation()
  {
    if (MONITORSERVICESIMPLSERVICE_EXCEPTION != null)
    {
      throw MONITORSERVICESIMPLSERVICE_EXCEPTION;
    }
    return MONITORSERVICESIMPLSERVICE_WSDL_LOCATION;
  }

  /**
   * @return returns MonitorServices
   */
  @WebEndpoint(name = "MonitorServicesImplPort")
  public MonitorServices getMonitorServicesImplPort()
  {
    return super.getPort(
        new QName("http://services.server.ws.monitor.stgmastek.com/", "MonitorServicesImplPort"),
        MonitorServices.class);
  }

  /**
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   * Supported features not in the <code>features</code> parameter will have their default values.
   * @return returns MonitorServices
   */
  @WebEndpoint(name = "MonitorServicesImplPort")
  public MonitorServices getMonitorServicesImplPort(WebServiceFeature... features)
  {
    return super.getPort(
        new QName("http://services.server.ws.monitor.stgmastek.com/", "MonitorServicesImplPort"),
        MonitorServices.class, features);
  }

}
