
package com.majescomastek.stgicd.ws.meta.whatifinterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.majescomastek.stgicd.ws.meta.authentication.Authentication;
import com.majescomastek.stgicd.ws.meta.whatifinterface.whatifinterface.ResponseTransactionSchedule;
import com.majescomastek.stgicd.ws.meta.whatifinterface.whatifinterface.WhatIfTransactionSchedule;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WhatIfInterface", targetNamespace = "http://com/majescomastek/stgicd/ws/meta/whatifinterface")
@XmlSeeAlso({
    com.majescomastek.stgicd.ws.meta.authentication.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.whatifinterface.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.whatifinterface.requestheader.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.whatifinterface.requestresponse.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.whatifinterface.transaction.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.whatifinterface.transaction.inboundwhatiftransactiondetail.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.whatifinterface.transactionresponse.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.whatifinterface.transactionresponse.inboundwhatiftransactiondetail.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.whatifinterface.transactionresponse.inboundwhatiftransactiondetail.installmentschedulesummarybyduedate.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.whatifinterface.whatifinterface.ObjectFactory.class
})
public interface WhatIfInterface {


    /**
     * 
     * @param userAuthentication
     * @param inputMsg
     * @return
     *     returns com.majescomastek.stgicd.ws.meta.whatifinterface.whatifinterface.ResponseTransactionSchedule
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "service", targetNamespace = "http://com/majescomastek/stgicd/ws/meta/whatifinterface", className = "com.majescomastek.stgicd.ws.meta.whatifinterface.Service")
    @ResponseWrapper(localName = "serviceResponse", targetNamespace = "http://com/majescomastek/stgicd/ws/meta/whatifinterface", className = "com.majescomastek.stgicd.ws.meta.whatifinterface.ServiceResponse")
    public ResponseTransactionSchedule service(
        @WebParam(name = "inputMsg", targetNamespace = "")
        WhatIfTransactionSchedule inputMsg,
        @WebParam(name = "UserAuthentication", targetNamespace = "")
        Authentication userAuthentication)
        throws Exception_Exception
    ;

}
