package com.nd.ws.billing.account.update;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "AccountUpdateInterface",
                  targetNamespace = "http://com/nd/ws/billing/account/update",
                  wsdlLocation = "/META-INF/wsdl/AccountUpdateInterface.wsdl")
public class AccountUpdateInterface extends Service
{

    private final static URL ACCOUNTUPDATEINTERFACE_WSDL_LOCATION;

    private final static WebServiceException ACCOUNTUPDATEINTERFACE_EXCEPTION;

    private final static QName ACCOUNTUPDATEINTERFACE_QNAME = new QName(
        "http://com/nd/ws/billing/account/update",
        "AccountUpdateInterface");

    static
    {
        ACCOUNTUPDATEINTERFACE_WSDL_LOCATION =
            com.nd.ws.billing.account.update.AccountUpdateInterface.class
                .getResource("/META-INF/wsdl/AccountUpdateInterface.wsdl");
        WebServiceException e = null;
        if (ACCOUNTUPDATEINTERFACE_WSDL_LOCATION == null)
        {
            e = new WebServiceException(
                "Cannot find '/META-INF/wsdl/AccountUpdateInterface.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        ACCOUNTUPDATEINTERFACE_EXCEPTION = e;
    }

    public AccountUpdateInterface()
    {
        super(__getWsdlLocation(), ACCOUNTUPDATEINTERFACE_QNAME);
    }

    private static URL __getWsdlLocation()
    {
        if (ACCOUNTUPDATEINTERFACE_EXCEPTION != null)
        {
            throw ACCOUNTUPDATEINTERFACE_EXCEPTION;
        }
        return ACCOUNTUPDATEINTERFACE_WSDL_LOCATION;
    }

    public AccountUpdateInterface(WebServiceFeature... features)
    {
        super(__getWsdlLocation(), ACCOUNTUPDATEINTERFACE_QNAME, features);
    }

    public AccountUpdateInterface(URL wsdlLocation)
    {
        super(wsdlLocation, ACCOUNTUPDATEINTERFACE_QNAME);
    }

    public AccountUpdateInterface(URL wsdlLocation,
                                  WebServiceFeature... features
                                 )
    {
        super(wsdlLocation, ACCOUNTUPDATEINTERFACE_QNAME, features);
    }

    public AccountUpdateInterface(URL wsdlLocation, QName serviceName)
    {
        super(wsdlLocation, serviceName);
    }

    public AccountUpdateInterface(URL wsdlLocation, QName serviceName,
                                  WebServiceFeature... features
                                 )
    {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns IAccountUpdateInterface
     */
    @WebEndpoint(name = "AccountUpdateInterfacePort")
    public IAccountUpdateInterface getAccountUpdateInterfacePort()
    {
        return super
            .getPort(new QName("http://com/nd/ws/billing/account/update",
                               "AccountUpdateInterfacePort"),
                     IAccountUpdateInterface.class);
    }

    /**
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     *
     * @return returns IAccountUpdateInterface
     */
    @WebEndpoint(name = "AccountUpdateInterfacePort")
    public IAccountUpdateInterface getAccountUpdateInterfacePort(
        WebServiceFeature... features
                                                                )
    {
        return super
            .getPort(new QName("http://com/nd/ws/billing/account/update",
                               "AccountUpdateInterfacePort"),
                     IAccountUpdateInterface.class,
                     features);
    }
}
