package com.nd.ws.billing.account.update;

import com.nd.ws.billing.account.updateinterface.AccountWorkflowRequest;
import com.nd.ws.billing.account.updateinterface.AccountWorkflowResponse;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebService(name = "IAccountUpdateInterface",
            targetNamespace = "http://com/nd/ws/billing/account/updateinterface")
@XmlSeeAlso({com.nd.ws.billing.account.updateinterface.ObjectFactory.class,
             com.nd.billing.model.account.response.ObjectFactory.class})
public interface IAccountUpdateInterface
{


    /**
     * @return returns com.nd.ws.billing.account.updateinterface.AccountWorkflowResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "executeAccountUpdate",
                    targetNamespace = "http://com/nd/ws/billing/account/updateinterface",
                    className = "com.nd.ws.billing.account.updateinterface.ExecuteAccountUpdate")
    @ResponseWrapper(localName = "executeAccountUpdateResponse",
                     targetNamespace = "http://com/nd/ws/billing/account/updateinterface",
                     className = "com.nd.ws.billing.account.updateinterface.ExecuteAccountUpdateResponse")
    @Action(input = "http://com/nd/ws/billing/account/updateinterface/IAccountUpdateInterface/executeAccountUpdateRequest",
            output = "http://com/nd/ws/billing/account/updateinterface/IAccountUpdateInterface/executeAccountUpdateResponse",
            fault = {@FaultAction(className = ExceptionException.class,
                                  value = "http://com/nd/ws/billing/account/updateinterface/IAccountUpdateInterface/executeAccountUpdate/Fault/Exception_Exception")})
    public AccountWorkflowResponse executeAccountUpdate(
        @WebParam(name = "AccountWorkflowRequest",
                  targetNamespace = "") AccountWorkflowRequest accountWorkflowRequest
                                                       )
    throws ExceptionException;
}
