
package com.majescomastek.stgicd.ws.meta.premiuminterfacend;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.majescomastek.stgicd.ws.meta.authentication.Authentication;
import com.majescomastek.stgicd.ws.meta.premiuminterfacend.premiuminterfacend.InboundPremiumTransaction;
import com.majescomastek.stgicd.ws.meta.premiuminterfacend.premiuminterfacend.OutputTransaction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PremiumInterfaceND", targetNamespace = "http://com/majescomastek/stgicd/ws/meta/premiuminterfacend")
@XmlSeeAlso({
    com.majescomastek.stgicd.ws.meta.authentication.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.premiuminterfacend.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.premiuminterfacend.premiuminterfacend.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.premiuminterfacend.requestheader.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.premiuminterfacend.requestresponse.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.premiuminterfacend.transaction.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.premiuminterfacend.transaction.inboundentity.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.premiuminterfacend.transaction.receivabledetails.ObjectFactory.class,
    com.majescomastek.stgicd.ws.meta.premiuminterfacend.transactionresponse.ObjectFactory.class
})
public interface PremiumInterfaceND {


    /**
     * 
     * @param userAuthentication
     * @param inputMsg
     * @return
     *     returns com.majescomastek.stgicd.ws.meta.premiuminterfacend.premiuminterfacend.OutputTransaction
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "service", targetNamespace = "http://com/majescomastek/stgicd/ws/meta/premiuminterfacend", className = "com.majescomastek.stgicd.ws.meta.premiuminterfacend.Service")
    @ResponseWrapper(localName = "serviceResponse", targetNamespace = "http://com/majescomastek/stgicd/ws/meta/premiuminterfacend", className = "com.majescomastek.stgicd.ws.meta.premiuminterfacend.ServiceResponse")
    public OutputTransaction service(
        @WebParam(name = "inputMsg", targetNamespace = "")
        InboundPremiumTransaction inputMsg,
        @WebParam(name = "UserAuthentication", targetNamespace = "")
        Authentication userAuthentication)
        throws Exception_Exception
    ;

}
